#!/usr/bin/env python

import asyncio
import logging
import functools
import signal
import argparse

from profamaster.web import start_server
from profamaster.orders import exec_orders_in_queue
from profamaster.config import (
    CONFIG,
    CONFIG_FILE,
)
from profamaster.shiftpi.shiftpi import (
    LOW,
    startupMode,
    shiftRegisters
)

logger = logging.getLogger(__name__)


def ask_exit(signame):
    logger.info("got signal %s: exit" % signame)
    loop.stop()


def custom_exception_handler(loop, context):
    # first, handle with default handler
    loop.default_exception_handler(context)

    exception = context.get('exception')
    logger.exception(str(exception))
    loop.stop()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', '-c', type=argparse.FileType('r'))
    args = parser.parse_args()
    config_file = args.config
    CONFIG_FILE = config_file  # noqa
    CONFIG = CONFIG()
    loop = asyncio.get_event_loop()
    loop.set_exception_handler(custom_exception_handler)
    for signame in ('SIGINT', 'SIGTERM'):
        loop.add_signal_handler(getattr(signal, signame),
                                functools.partial(ask_exit, signame))
    try:
        logger.debug('start server')
        shiftRegisters(CONFIG['registers_nb'])
        startupMode(LOW)
        loop.create_task(start_server())
        loop.create_task(exec_orders_in_queue())
        loop.run_forever()
    except KeyboardInterrupt:
        logger.debug('Ctrl+C pressed, stopping')
